### PR TITLE
Data ingested into myria is now stored under /mnt

### PR DESCRIPTION
**Pull request by lbrendanl**
Changed the initial configuration of myria so that the postgres
data_directoy points to the /mnt drive attached with star cluster
rather than the default postgres location.

Also it appears my editor removed some spaces at the end of some lines, sorry for the clutter.

### CODE REVIEW

**Comment by BrandonHaynes** [comment]
I moved the responsibility for actually changing the data directory into the postgres plugin, rather than letting the myria plugin handle it.  This prevented creating another myria->postgres dependency.  

I also refactored the `set_data_directory` function a bit to automatically detect the original data directory (rather than requiring it as a parameter) and did a bet of defensive tuning on the sed expressions.

@lbrendanl : any issues with these changes?

**Comment by lbrendanl** [comment]
@BrandonHaynes that all sounds good to me

**Comment by jortiz16** [comment]
@BrandonHaynes  I think there might be an issue.  I tried to create a cluster after your commits, but I get the following permission error from postgres: 

```
!!! ERROR - Error occured while running plugin 'postgresplugin':
!!! ERROR - error occurred in job (id=brendanTest-node004): remote command 'source /etc/profile && sudo service postgresql start' failed with status 1:
* Starting PostgreSQL 9.1 database server
* The PostgreSQL server failed to start. Please check the log output:
2015-04-02 23:56:10 GMT FATAL:  data directory "/mnt/postgresdata" has group or world access
2015-04-02 23:56:10 GMT DETAIL:  Permissions should be u=rwx (0700).
...fail!
```

I asked @lbrendanl too and he also gets the same error. I have crash-report dumps of this error I can send to you in case that is helpful. I'm not sure which commit caused this, but when I rolled back to the commit from March 8th, I do not get this problem.

**Comment by BrandonHaynes** [comment]
@jortiz16 @lbrendanl -- this should now be corrected.

**Comment by lbrendanl** [comment]
@BrandonHaynes Did a test run of this, and it all looks good.

**Pull request merged**
